/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/quanxiang-cloud/overseer/pkg/apis/overseer/v1alpha1"
	scheme "github.com/quanxiang-cloud/overseer/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OverseersGetter has a method to return a OverseerInterface.
// A group's client should implement this interface.
type OverseersGetter interface {
	Overseers(namespace string) OverseerInterface
}

// OverseerInterface has methods to work with Overseer resources.
type OverseerInterface interface {
	Create(ctx context.Context, overseer *v1alpha1.Overseer, opts v1.CreateOptions) (*v1alpha1.Overseer, error)
	Update(ctx context.Context, overseer *v1alpha1.Overseer, opts v1.UpdateOptions) (*v1alpha1.Overseer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Overseer, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OverseerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Overseer, err error)
	OverseerExpansion
}

// overseers implements OverseerInterface
type overseers struct {
	client rest.Interface
	ns     string
}

// newOverseers returns a Overseers
func newOverseers(c *OverseerV1alpha1Client, namespace string) *overseers {
	return &overseers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the overseer, and returns the corresponding overseer object, and an error if there is any.
func (c *overseers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Overseer, err error) {
	result = &v1alpha1.Overseer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("overseers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Overseers that match those selectors.
func (c *overseers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OverseerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OverseerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("overseers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested overseers.
func (c *overseers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("overseers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a overseer and creates it.  Returns the server's representation of the overseer, and an error, if there is any.
func (c *overseers) Create(ctx context.Context, overseer *v1alpha1.Overseer, opts v1.CreateOptions) (result *v1alpha1.Overseer, err error) {
	result = &v1alpha1.Overseer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("overseers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(overseer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a overseer and updates it. Returns the server's representation of the overseer, and an error, if there is any.
func (c *overseers) Update(ctx context.Context, overseer *v1alpha1.Overseer, opts v1.UpdateOptions) (result *v1alpha1.Overseer, err error) {
	result = &v1alpha1.Overseer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("overseers").
		Name(overseer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(overseer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the overseer and deletes it. Returns an error if one occurs.
func (c *overseers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("overseers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *overseers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("overseers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched overseer.
func (c *overseers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Overseer, err error) {
	result = &v1alpha1.Overseer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("overseers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
